global proc selectFingers(){
if (`objExists L_thumb_01_ctrl_jnt`)
{ 
select -r L_thumb_01_ctrl_jnt;
}

if (`objExists L_index_01_ctrl_jnt`)
{ 
select -add L_index_01_ctrl_jnt;
}

if (`objExists L_middle_01_ctrl_jnt`)
{ 
select -add L_middle_01_ctrl_jnt;
}

if (`objExists L_ring_01_ctrl_jnt`)
{ 
select -add L_ring_01_ctrl_jnt;
}

if (`objExists L_pinky_01_ctrl_jnt`)
{ 
select -add L_pinky_01_ctrl_jnt;
}
}